import Head from 'next/head'
import {ProjectsGallery} from '../components/ProjectsGallery'
import { Shell } from '../components/Shell'
import styles from '../styles/Home.module.css'

const Projects = () => (
  <div className={styles.container}>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Shell location="projects">
      <ProjectsGallery></ProjectsGallery>
    </Shell>
  </div>
)

export default Projects